UX issues
thegoodparty/tgp-webapp pull request #136
Opened 2021-02-06 08:25 UTC by webdeveloper001

## THE GOOD PARTY

### Description

### Ticket
https://www.notion.so/thegoodparty/

### Before

### After

### Dependencies

2021-02-06 19:18 UTC, tomer-tgp requested changes

2021-02-06 19:18 UTC, tomer-tgp commented on components/elections/CandidateNewWrapper/CompareCandidate.js
>    margin-top: 25px;
this should be `margin: 25px 15px 0`

2021-02-06 19:18 UTC, tomer-tgp commented on components/elections/CandidateNewWrapper/Main.js
> +    // top: 180px;
remove comments

2021-02-06 19:18 UTC, tomer-tgp commented on components/elections/CandidateNewWrapper/Main.js
> +    // top: 180px;
remove comments

2021-02-06 19:18 UTC, tomer-tgp commented on components/elections/CandidateNewWrapper/Main.js
> +        </ComparedCandidateWrapper>
Let's move the entire carousel to its own file/components to keep that logic separate.
Also, you need a key on the compareCandidate

2021-02-06 19:18 UTC, tomer-tgp commented on components/elections/CandidateNewWrapper/index.js
> +  // padding: 0 20px;
remove comments

2021-02-06 19:18 UTC, tomer-tgp commented on theme/breakpoints.js
> +  xl: '1200px',
these should match material-ui breakpoints, so the grid and everything else will match
https://material-ui.com/customization/breakpoints/

2021-02-08 10:55 UTC, webdeveloper001 commented on theme/breakpoints.js
> +  xl: '1200px',
@tomer-tgp , I followed our design. 
Our designers are building three versions > 1024,1024-1200, 1200 <
To match material-ui breakpoints, we should let them use 960 instead of 1024 and 1280 instead of 1200.

2021-02-08 20:21 UTC, tomer-tgp approved these changes

2021-02-08 20:22 UTC, merged