Tgp 738
thegoodparty/tgp-webapp pull request #138
Opened 2021-02-15 17:14 UTC by webdeveloper001

## THE GOOD PARTY

### Description

### Ticket
https://www.notion.so/thegoodparty/

### Before

### After

### Dependencies

2021-02-16 00:34 UTC, tomer-tgp requested changes

2021-02-16 00:34 UTC, tomer-tgp commented on components/elections/CandidateNewWrapper/ProfileInfo.js
> +import * as htmlToImage from 'html-to-image';
hmmm, we don't need to include that in the view of the candidate. Not everyone who sees the candidate needs to generate an image

2021-02-16 00:34 UTC, tomer-tgp commented on components/elections/ShareImageWrapper/index.js
> +import Typography from '@material-ui/core/Typography';
we have styledguide for text, use ours

2021-02-16 00:34 UTC, tomer-tgp commented on components/elections/ShareImageWrapper/index.js
> +      });
nono. We need a different route for this, that is not accessible for the users. It will be called from a cron job and generate the image. We will have thousands of views a day for this and we only need to generate the image once

2021-02-16 16:28 UTC, webdeveloper001 commented on components/elections/ShareImageWrapper/index.js
> +      });
@tomer-tgp , this component is not for the new candidate page. we have a new route for this.
/share-image/3

2021-02-17 09:13 UTC, tomer-tgp requested changes

2021-02-17 09:13 UTC, tomer-tgp commented on components/elections/CandidateNewWrapper/ProfileInfo.js
> +=======
remove conflicts code

2021-02-17 09:13 UTC, tomer-tgp commented on components/elections/CandidateNewWrapper/ProfileInfo.js
> +>>>>>>> 887072a82f72cf8e4351dffca28008c6fcc1c019
conflicts

2021-02-17 09:13 UTC, tomer-tgp commented on components/elections/CandidateNewWrapper/ProfileInfo.js
> +>>>>>>> 887072a82f72cf8e4351dffca28008c6fcc1c019
conflicts

2021-02-17 09:13 UTC, tomer-tgp commented on components/elections/ShareImageWrapper/index.js
> +function ProfileInfo({ candidate, shareImageCallback }) {
match file name

2021-02-17 18:13 UTC, tomer-tgp requested changes

2021-02-17 18:13 UTC, tomer-tgp commented on components/elections/CandidateNewWrapper/ProfileInfo.js
> +>>>>>>> 887072a82f72cf8e4351dffca28008c6fcc1c019
still an issue, how is this working locally for you??

2021-02-18 05:12 UTC, tomer-tgp approved these changes

2021-02-18 05:12 UTC, merged