7243 - fix display name update issue/avatar issue
thegoodparty/tgp-webapp pull request #220
Opened 2022-01-24 11:44 UTC by webdeveloper001

## THE GOOD PARTY

### Description

### Ticket
https://www.notion.so/thegoodparty/

### Before

### After

### Dependencies

2022-01-24 23:04 UTC, tomer-tgp requested changes

2022-01-24 23:04 UTC, tomer-tgp commented on components/profile/ProfileSettingsWrapper/ImageSection.js
> +          {getName(user)}
is that the only place we are using it? in the candidate page on the feed we should use that too

2022-01-25 19:34 UTC, webdeveloper001 commented on components/profile/ProfileSettingsWrapper/ImageSection.js
> +          {getName(user)}
Got it, Let me check @tomer-tgp

2022-01-25 21:05 UTC, tomer-tgp requested changes

2022-01-25 21:05 UTC, tomer-tgp commented on components/profile/ProfileSettingsWrapper/ImageSection.js
> +          {getName(user)}
I am not seeing that change yet.

2022-01-25 21:10 UTC, tomer-tgp commented
Also please change getName() with getDisplayName()

2022-01-25 21:19 UTC, tomer-tgp requested changes

2022-01-25 21:19 UTC, tomer-tgp commented on components/elections/CandidateNewWrapper/RecentlyJoined.js
> +      return getDisplayName(supporter.user);
I think this requires a backend change so we pass the displayName for the supporter as well.

2022-01-25 22:03 UTC, tomer-tgp requested changes

2022-01-25 22:03 UTC, tomer-tgp commented on components/elections/CandidateNewWrapper/RecentlyJoined.js
> +      return getDisplayName(supporter.user);
based on the way we did it on the backend we should go back to what was there before:
`return supporter.user.name;`

2022-01-25 22:29 UTC, tomer-tgp approved these changes

2022-01-25 22:29 UTC, merged