fix issue for update email
thegoodparty/tgp-webapp pull request #222
Opened 2022-01-24 19:28 UTC by webdeveloper001

## THE GOOD PARTY

### Description

### Ticket
https://www.notion.so/thegoodparty/

### Before

### After

### Dependencies

2022-01-24 23:02 UTC, tomer-tgp requested changes

2022-01-24 23:02 UTC, tomer-tgp commented on components/profile/ProfileSettingsWrapper/PersonalSection.js
> +      localStorage.setItem('verifiedEmail', user.email);
We are using mostly cookies. Why use localStorage here?
If you want to use local storage, please create a separate helper for it.

2022-01-24 23:02 UTC, tomer-tgp commented on components/profile/ProfileSettingsWrapper/PersonalSection.js
> +      localStorage.setItem('verifiedEmail', user.email);
I have a helper I used before if you want I can send it to you so you can reuse it. Let me know over slack.
Or just use our cookie helper instead.

2022-01-25 19:33 UTC, webdeveloper001 commented on components/profile/ProfileSettingsWrapper/PersonalSection.js
> +      localStorage.setItem('verifiedEmail', user.email);
Got it, @tomer-tgp

2022-01-25 21:02 UTC, tomer-tgp approved these changes

2022-01-25 21:03 UTC, merged